# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Andrei Rosu"
description: > # this means to ignore newlines until "email:"


email: andi.rosu@gmail.com
#blog logo
logo: "/assets/images/ar_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/bg.jpg"

name: 'Andrei Rosu'
author: 'Andrei Rosu'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://andreirosu.online.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@andi_rosu'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/andi.rosu
    desc: Facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/andiro23
    desc:	Github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
